server:
  port: ${PORT:6666}


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:thesis}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:quyvx}
    password: ${DB_PASSWORD:quy09082002}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  keys:
    private_key_path: ${JWT_PRIVATE_KEY_PATH:classpath:/keys/jwtRS256.key}
    public_key_path: ${JWT_PUBLIC_KEY_PATH:classpath:/keys/jwtRS256.key.pub}
  access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRE:60}
  refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRE:10080}

google:
  cloud:
    storage:
      bucket-name: ${GOOGLE_CLOUD_STORAGE_BUCKET_NAME:data_image_car}